### ISSUE TITLE
复制上wt的配置文件后乱码了emmmm 有解决办法吗。。

### ISSUE THREAD

**Issue by moshuiNW** [jiaxinaoliao/neovimBeginCpp#5]
<img width="1102" alt="2023-11-01_153338" src="https://github.com/jiaxinaoliao/neovimBeginCpp/assets/110805397/6476ac0d-e3e9-4e86-a4b1-03087543a83f">

**Comment by jiaxinaoliao** [comment]
这个是字体的问题，改一下字体就行，改成nerdfont字体
________________________________
发件人: moshuiNW ***@***.***>
发送时间: 2023年11月1日 15:35
收件人: jiaxinaoliao/neovimBeginCpp ***@***.***>
抄送: Subscribed ***@***.***>
主题: [jiaxinaoliao/neovimBeginCpp] 复制上wt的配置文件后乱码了emmmm 有解决办法吗。。 (Issue #5)


[Uploading 2023-11-01_153338.png…]

―
